BUILD: Fix linking issues on debian
/usr/bin/ld: src/providers/test_search_bases-data_provider_be.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:7689: recipe for target 'test_search_bases' failed
make[3]: *** [test_search_bases] Error 1

/usr/bin/ld: src/providers/ad_access_filter_tests-data_provider_be.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:6457: recipe for target 'ad_access_filter_tests' failed
make[3]: *** [ad_access_filter_tests] Error 1

/usr/bin/ld: src/providers/ad_common_tests-data_provider_be.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:6517: recipe for target 'ad_common_tests' failed
make[3]: *** [ad_common_tests] Error 1

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>