Makefile: Add missing library to the dp_opt_tests
dp_opt_tests cannot be linked properly if link_all_deplibs is disabled (debian)

/usr/bin/ld: src/tests/cmocka/dp_opt_tests-test_dp_opts.o:
    undefined reference to symbol 'poptFreeContext@@LIBPOPT_0'
/usr/bin/ld: note: 'poptFreeContext@@LIBPOPT_0' is defined in DSO
/lib64/libpopt.so.0 so try adding it to the linker command line
/lib64/libpopt.so.0: could not read symbols: Invalid operation

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>