MONITOR: Disable inlining of function load_configuration
This reverts commit cff89439b21f8573c6896b09cb1a8d5f9de3144c.

The previous fix was not sufficient and similar warning appears after different
change in function load_configuration.

src/monitor/monitor.c: In function ‘main’:
src/monitor/monitor.c:2962:24: error: ‘monitor’ may be used uninitialized
                               in this function [-Werror=maybe-uninitialized]
     monitor->is_daemon = !opt_interactive;
                        ^
cc1: all warnings being treated as errors

It's better to disable optimisation of function load_configuration after fail
in chown(unlink) instead of checking errno for 0 and overriding it with EINVAL.

Reviewed-by: Michal Židek <mzidek@redhat.com>