intg: prevent "TypeError: must be type, not classobj"
http://stackoverflow.com/questions/9698614/super-raises-typeerror-must-be-type-not-classobj-for-new-style-class

========================== ERRORS ===========================
_______ ERROR at setup of test_regression_ticket2163 ________
Traceback (most recent call last):
  File "src/tests/intg/test_pysss_nss_idmap.py", line 48, in ad_inst
    instance.teardown()
  File "src/tests/intg/ds_openldap.py", line 371, in teardown
    super(FakeAD, self).teardown()
TypeError: super() argument 1 must be type, not classobj

Reviewed-by: Fabiano Fidêncio <fidencio@redhat.com>
Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit 948c1a4d423dba289342844fb177bd5fa9828fc0)