intg: Return list for enumeration functions
The documentation of get_passwd_list/get_group_list
says that they return group/user database entry list.
However, ther return class 'map' with python3 due to
changes in high level function "map".

Traceback (most recent call last):
  File "/dev/shm/sssd/src/tests/intg/ent_test.py",
       line 141, in test_assert_passwd_list
    ent.assert_passwd_list(ent.contains())
  File "/dev/shm/sssd/src/tests/intg/ent.py",
       line 243, in assert_passwd_list
    assert not d, d
AssertionError: not a list, <class 'map'>

Reviewed-by: Martin Basti <mbasti@redhat.com>