Fix compilation with python3.6
Autotools does not generate defines in conditional way (ifndef .. define)
and therefore it might happen that "defines" in config.h migt redefine
some macros in different way and generate a warning.

e.g.
  In file included from /home/build/sssd/src/util/util.h:24:0,
                   from /home/build/sssd/src/python/pyhbac.c:24:
  ./config.h:322:0: error: "HAVE_LONG_LONG" redefined [-Werror]
   #define HAVE_LONG_LONG 1

  In file included from /usr/include/python3.6m/Python.h:50:0,
                   from /home/build/sssd/src/python/pyhbac.c:21:
  /usr/include/python3.6m/pyport.h:42:0: note: this is the location of the previous definition
   #define HAVE_LONG_LONG

We need to include config.h before Python.h to avoid redefinition of
HAVE_LONG_LONG which is definded conditionally in Python.h

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>