BUILD: Fix linking of ad_common_tests on debian
/usr/bin/ld: src/providers/ad/ad_common_tests-ad_domain_info.o:
     undefined reference to symbol 'idmap_error_string@@SSS_IDMAP_0.4'
/dev/shm/13/.libs/libsss_idmap.so.0:
     error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:9169: recipe for target 'ad_common_tests' failed

Reviewed-by: Lukáš Slebodník <lslebodn@redhat.com> (oneliner-rule)