Fix warning sign-compare
python3.5 CFLAGS contains warning Wsign-compare and file confdb_setup.c
was added to SSSD_TOOLS_OBJ which is required for python3-sss (pysss.so)

src/confdb/confdb_setup.c: In function 'confdb_purge':
src/confdb/confdb_setup.c:95:15: error: comparison between signed and unsigned
  integer expressions [-Werror=sign-compare]
     for(i=0; i<res->count; i++) {
               ^
src/confdb/confdb_setup.c: In function 'confdb_init_db':
src/confdb/confdb_setup.c:219:25: error: comparison between signed and unsigned
  integer expressions [-Werror=sign-compare]
     if (ret <= 0 || ret >= sizeof(timestr)) {
                         ^
cc1: all warnings being treated as errors

Reviewed-by: Michal Židek <mzidek@redhat.com>