sssctl: Fix warning maybe-uninitialized
It looks like some special gcc optimalisation and special case
may cause to have unitialized output argument _dom when return
code is EOK

src/tools/sssctl/sssctl_cache.c: In function ‘sssctl_print_object’:
src/tools/sssctl/sssctl_cache.c:491:8: error: ‘dom’ may be used
  uninitialized in this function [-Werror=maybe-uninitialized]
     if (dom == NULL) {
        ^
src/tools/sssctl/sssctl_cache.c:447:15: error: ‘entry’ may be used
  uninitialized in this function [-Werror=maybe-uninitialized]
     *_entry = talloc_steal(mem_ctx, entry);
               ^~~~~~~~~~~~
src/tools/sssctl/sssctl_cache.c:412:25: note: ‘entry’ was declared here
     struct sysdb_attrs *entry;
                         ^~~~~

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>