sssctl: Fix missing declaration
The WEXITSTATUS is defined in stdlib.h on linux.
There is a nice comment in stdlib.h:
  /* Define the macros <sys/wait.h> also would define this way.  */

It's better to not rely on this and use more platfom friendly
way with including "sys/wait.h". For example the libc on FreeBSD
does not provide WEXITSTATUS in stdlib.h.

I found this macro mentioned only in the manual page for wait(2)
and there is mentioned just the "sys/wait.h" and not "stdlib.h"

src/tools/sssctl/sssctl.c: In function 'sssctl_run_command':
src/tools/sssctl/sssctl.c:110: error: implicit declaration of function
'WEXITSTATUS'
gmake[2]: *** [Makefile:22383: src/tools/sssctl/sssctl-sssctl.o] Error 1

Reviewed-by: Fabiano Fidêncio <fidencio@redhat.com>
(cherry picked from commit 73c9330fa3de6912e45c1ab686d5290f143b8352)