sbus request: fix error initialization
fixes:
sssd_dbus_request.c:28:1: error: missing initializer [-Werror=missing-field-initializers]
sssd_dbus_request.c:28:1: error: (near initialization for 'error_internal.dummy1') [-Werror=missing-field-initializers]

(cherry picked from commit 8779b9ee101ed3e5a6836b5366c006dc21dd36c0)