data_provider/dp_target_id: remove store statement from a never read variable
The same variable was set twice to a value that was never read:
```
Error: CLANG_WARNING:
sssd-2.3.0/src/providers/data_provider/dp_target_id.c:197:9: warning:
Value stored to 'ret' is never read
 #        ret = ENOMEM;
 #        ^     ~~~~~~
sssd-2.3.0/src/providers/data_provider/dp_target_id.c:197:9: note:
Value stored to 'ret' is never read
 #        ret = ENOMEM;
 #        ^     ~~~~~~
 #  195|           DEBUG(SSSDBG_CRIT_FAILURE,
 #  196|                 "Failed creating temporary talloc context\n");
 #  197|->         ret = ENOMEM;
 #  198|           goto done;
 #  199|       }

Error: CLANG_WARNING:
sssd-2.3.0/src/providers/data_provider/dp_target_id.c:308:9: warning:
Value stored to 'ret' is never read
 #        ret = ENOMEM;
 #        ^     ~~~~~~
sssd-2.3.0/src/providers/data_provider/dp_target_id.c:308:9: note:
Value stored to 'ret' is never read
 #        ret = ENOMEM;
 #        ^     ~~~~~~
 #  306|           DEBUG(SSSDBG_CRIT_FAILURE,
 #  307|                 "Failed creating attributes\n");
 #  308|->         ret = ENOMEM;
 #  309|           goto done;
 #  310|       }
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>