SBUS: Silence warning maybe-uninitialized
It should not happen because function sbus_interface_find_property
should return NULL for access different than SBUS_PROPERTY_READABLE
or SBUS_PROPERTY_WRITABLE. And thus we would return ERR_SBUS_UNKNOWN_PROPERTY
from the function sbus_request_property.

src/sbus/interface/sbus_properties.c: In function 'sbus_request_property.isra.0':
src/sbus/interface/sbus_properties.c:360:14:
  error: 'type' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]
     sbus_req = sbus_request_create(mem_ctx, conn, type, destination,
     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    interface_name, property_name, path);
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Merges: https://pagure.io/SSSD/sssd/pull-request/3851

Reviewed-by: Pavel Březina <pbrezina@redhat.com>