PROXY: Fix warning-format-overflow directive argument is null
  CC       src/providers/proxy/libsss_proxy_la-proxy_id.lo
In file included from src/util/util.h:47,
                 from src/providers/proxy/proxy.h:35,
                 from src/providers/proxy/proxy_id.c:30:
In function ‘delete_user’,
    inlined from ‘get_pw_uid’ at src/providers/proxy/proxy_id.c:383:15,
    inlined from ‘proxy_account_info’ at src/providers/proxy/proxy_id.c:1617:19,
    inlined from ‘proxy_account_info_handler_send’ at src/providers/proxy/proxy_id.c:1760:20:
src/util/debug.h:126:9: error: ‘%s’ directive argument is null
[-Werror=format-overflow=]
  126 |         sss_debug_fn(__FILE__, __LINE__, __FUNCTION__, \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  127 |                      __debug_macro_level, \
      |                      ~~~~~~~~~~~~~~~~~~~~~~
  128 |                      format, ##__VA_ARGS__); \
      |                      ~~~~~~~~~~~~~~~~~~~~~~
src/providers/proxy/proxy_id.c:215:5: note: in expansion of macro ‘DEBUG’
  215 |     DEBUG(SSSDBG_TRACE_FUNC,
      |     ^~~~~
src/providers/proxy/proxy_id.c: In function ‘proxy_account_info_handler_send’:
src/providers/proxy/proxy_id.c:216:17: note: format string is defined here
  216 |           "User %s does not exist (or is invalid) on remote server,"
      |                 ^~

Reviewed-by: Sumit Bose <sbose@redhat.com>