BUILD: Link test_data_provider_be with -ldl
The module data_provider_be.o uses uncfion dlsym and
thus need to be linked with -ldl.

/usr/bin/ld: src/providers/test_data_provider_be-data_provider_be.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:10461: recipe for target 'test_data_provider_be' failed

It was not a problem when sssd was compiled with NSS because it contains -ldl
among its flags.
NSS_LIBS='-lssl3 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lpthread -ldl '

However the compilation failed when sssd was compiled with libcrypto

Reviewed-by: Michal Židek <mzidek@redhat.com>