KCM: supress false positive cppcheck warnings
Supress a bunch of warnings like this:
```
Error: CPPCHECK_WARNING (CWE-456):
sssd-2.3.2/src/responder/kcm/kcmsrv_ccache_json.c:154: error[uninitvar]: Uninitialized variable: key_uuid
 #  152|       uuid_t key_uuid;
 #  153|
 #  154|->     ret = sec_key_get_uuid(sec_key, key_uuid);
 #  155|       if (ret != EOK) {
 #  156|           DEBUG(SSSDBG_MINOR_FAILURE, "Cannot convert key to UUID\n");
```

Those are clearly false positives as in all those places `uuid` is output arg and
isn't read in following execution flow. "cppcheck" fails to detect this because
`uuid_t` and uuid_parse()/uuid_copy() are opaque for analyzer.

There is no sane way to initialize uuid_t in a way that would please cppcheck.
Moreover, it doesn't make sense to do so from performance point of view.
Hence suppression.

Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>