BUILD: Fix detection of pthread with strict CFLAGS
If the configure was called with stricter flags (-Werror=unused-variable)
then configure script did not detect tread safe initialisation.
As a result of this client code was not build with mutexes.

conftest.c: In function 'main':
conftest.c:39:17: error: unused variable 'm' [-Werror=unused-variable]
 pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;
                 ^
cc1: all warnings being treated as errors
configure:15331: $? = 1
configure:15338: WARNING: Pthread library not found! Clients will not be thread safe...

Reviewed-by: Pavel Březina <pbrezina@redhat.com>
(cherry picked from commit f775337a7d4ca1c0be8eab683d0d753cbaee49e2)