intg: remove unused is_secrets_socket()
Use of this function was removed in:
10069b1d39e671b7502c5211883c94ceaa91aebb

```
sssd/build/../src/tests/intg/getsockopt_wrapper.c:31:13: error: ‘is_secrets_socket’ defined but not used [-Werror=unused-function]
   31 | static bool is_secrets_socket(int fd)
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>