DEBUG: fix missing "va_end"
Fixes following warning:
```
Error: VARARGS (CWE-237):
sssd-2.6.0/src/util/debug.c:294: va_init: Initializing va_list "ap_fallback".
sssd-2.6.0/src/util/debug.c:305: missing_va_end: "va_end" was not called for "ap_fallback".
 #  303|                                  debug_chain_id, format);
 #  304|                   if (ret < 0) {
 #  305|->                     return;
 #  306|                   }
 #  307|                   result_fmt = chain_id_fmt_dyn;
```

Reviewed-by: Sumit Bose <sbose@redhat.com>