CLIENT:PAM: fixed missed return check
Return code of `prompt_2fa()` wasn't checked and
thus its fail wasn't properly processed.

Spotted with a help of following warning:
```
Error: CLANG_WARNING:
sssd-2.3.2/src/sss_client/pam_sss.c:2355:21: warning: Value stored to 'ret' is never read
 #                    ret = prompt_2fa(pamh, pi, _("First Factor (Current Password): "),
 #                    ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>