SYSDB-TESTS: Fix error too few arguments to function ‘_ck_assert_failed’
* add missing messages to fail_{if,unless} macros
* convert assertions to different macros

e.g.
src/tests/sysdb-tests.c:6622:5: error: too few arguments to function ‘_ck_assert_failed’
 6622 |     fail_if(ret != EOK);