Remove legacy script for upgrading sssd.conf
The script was mainly required to upgrade sssd.conf from version 1 to
version 2 which was done in sssd-0.6. All currently supported linux
distribution have at least sssd >= 1.8 and require 2nd version of
sssd.conf. Therefore upgrade does not make any sense.

There was an attempt to port this file to python3 as part of
ticket#2017 3 years ago. But it does not work and nobody noticed that
due to missing code coverage.

sh# ls -l /etc/sssd/sssd.conf
-rw-------. 1 root root 5372 Jan 24 21:09 /etc/sssd/sssd.conf

sh# python3 -m SSSDConfig.sssd_upgrade_config
ERROR: a bytes-like object is required, not 'str'

sh# ls -l /etc/sssd/sssd.conf
-rw-------. 1 root root 0 Jan 24 21:09 /etc/sssd/sssd.conf

Summary: The script does not make any sense today,
it is not used by anyone and it does not worth to keep it in upstream
anymore.