SIFP: Fix warning format-security
dbus-1.11.8 added attributes for format string check to
few functions in public header files. And therefore there is a warning.

src/lib/sifp/sss_sifp_utils.c: In function ‘sss_sifp_set_io_error’:
src/lib/sifp/sss_sifp_utils.c:44:5: error: format not a string literal
and no format arguments [-Werror=format-security]
     dbus_set_error(ctx->io_error, error->name, error->message);
          ^~~~~~~~~~~~~~