sssctl: Fix warning may be used uninitialized
gcc 7 probably does some new optimisations which might
cause few wariables to be uninitialized.

src/tools/sssctl/sssctl_cache.c: In function ‘sssctl_print_object’:
src/tools/sssctl/sssctl_cache.c:523:13: error: ‘dom’ may be used uninitialized
  in this function [-Werror=maybe-uninitialized]
         ret = info[i].attr_fn(tmp_ctx, entry, dom, info[i].attr, &value);
         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tools/sssctl/sssctl_cache.c:472:15: error: ‘entry’ may be used
  uninitialized in this function [-Werror=maybe-uninitialized]
     *_entry = talloc_steal(mem_ctx, entry);
               ^~~~~~~~~~~~
src/tools/sssctl/sssctl_cache.c:437:25: note: ‘entry’ was declared here
     struct sysdb_attrs *entry;
                         ^~~~~

Another workaround would be to remove static modifier
from function sssctl_find_object which probably prevents some
inlinig + optimisation.