CI: Build srpm fix for illegal version tag '-'
error: line 45: Illegal char '-' (0x2d) in: Version: sssd-2-7

Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>
Reviewed-by: Pavel Březina <pbrezina@redhat.com>
(cherry picked from commit ab89455be398f4688f95489b805c8ae204ba6f0d)