SPEC: Update spec file for krb5_local_auth_plugin
krb5_localauth_plugin could be build only with MIT kerberos >= 1.12.
However, this feature was backported in downstream to older version
of kerberos. So there were packaging failures

error: Installed (but unpackaged) file(s) found:
   /usr/lib/sssd/modules/sssd_krb5_localauth_plugin.so
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/sssd/modules/sssd_krb5_localauth_plugin.so
Child returncode was: 1
EXCEPTION: Command failed. See logs for output.

Reviewed-by: Petr Cech <pcech@redhat.com>
(cherry picked from commit b0ee27fd94f1d20d9c220754ae008a3189752287)