UTIL: mark non string array properly
Fixes:
```
../src/util/crypto/libcrypto/crypto_sha512crypt.c:48:5: error: initializer-string
for array of 'char' truncates NUL terminator but destination lacks 'nonstring'
attribute (65 chars into 64 available) [-Werror=unterminated-string-initialization]
   48 |     "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>
Reviewed-by: Sumit Bose <sbose@redhat.com>
(cherry picked from commit ee1c2d1779507f20bc63beb66077ccbcb4635970)