LDAP: Systemtap ldap probes fail without filter
SSSD systemtap probes for LDAP queries doesn't check the ldap search
filter. It's value can be NULL (means "no filter") and stap fails with

    ERROR: user string copy fault -14 at ...

This patch tests filter value before it is converted to printable
string and the filter is set to "<no filter>" in case of NULL value.

Reviewed-by: Michal Židek <mzidek@redhat.com>