Tests: Fix ipa test for gating.
Error: remote username contains invalid characters

Reviewed-by: Madhuri Upadhye <mupadhye@redhat.com>
(cherry picked from commit 23087669ef9826fbba9e3e6b379f2b0bb86c9820)