sss_client: Fix warning "_" redefined
"enum sss_authtok_type" is defined in sss_client/pam_message.h
So it's better to include it instead of "util/authtok.h".

"util/authtok.h" includes many header files including "util/util.h"

  CC       src/util/crypto/nss/libsss_crypt_la-nss_base64.lo
src/sss_client/pam_sss.c:48:0: error: "_" redefined [-Werror]
 #define _(STRING) dgettext (PACKAGE, STRING)
 ^
In file included from ../sssd/src/util/authtok.h:23:0,
                 from ../sssd/src/sss_client/pam_message.h:29,
                 from ../sssd/src/sss_client/pam_sss.c:43:
src/util/util.h:55:0: note: this is the location of the previous definition
 #define _(STRING) gettext (STRING)
 ^

Reviewed-by: Pavel Březina <pbrezina@redhat.com>