ci: remove old dependency repository
This repository is no longer needed and packages there are not maintained
for many years. Recent update of mock-core-configs changes `yum.conf` to
`dnf.conf` on Fedora and this breaks things for us.

The original purpose was to add newer libraries (such as ding-libs) to
RHEL-6 an early RHEL-7 so we could test current master there. This is no
longer needed since it contains up to date packages. Therefore it is safe
to remove it instead of trying to determine whether there should be yum.conf
or dnf.conf.

Otherwise we end up during mock build with:
```
KeyError: 'yum.conf'

ERROR: Error in configuration
```

Reviewed-by: Michal Židek <mzidek@redhat.com>
(cherry picked from commit feaf88914e61f871489481afd1eef5d5b11111c9)