PAM: fixes a couple of covscan issues
Fixes:
```
Error: COMPILER_WARNING (CWE-758):
sssd-2.4.3/src/util/debug.h:127:5: warning[-Wformat-overflow=]: '%.*s' directive argument is null
 #  127 |     sss_debug_fn(__FILE__, __LINE__, __FUNCTION__, \
 #      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #  128 |                  level, \
 #      |                  ~~~~~~~~
 #  129 |                  format, ##__VA_ARGS__); \
 #      |                  ~~~~~~~~~~~~~~~~~~~~~~
sssd-2.4.3/src/responder/pam/pamsrv_cmd.c: scope_hint: In function 'filter_responses'
sssd-2.4.3/src/responder/pam/pamsrv_cmd.c:569:51: note: format string is defined here
 #  569 |               "Found PAM ENV filter for variable [%.*s] and service [%s].\n",
 #      |                                                   ^~~~
```

and

```
Error: COMPILER_WARNING (CWE-758):
sssd-2.4.3/src/util/util.h:47: included_from: Included from here.
sssd-2.4.3/src/responder/pam/pamsrv_cmd.c:24: included_from: Included from here.
sssd-2.4.3/src/responder/pam/pamsrv_cmd.c: scope_hint: In function 'pam_check_user_search_next'
sssd-2.4.3/src/util/debug.h:127:5: warning[-Wformat-overflow=]: '%s' directive argument is null
 #  127 |     sss_debug_fn(__FILE__, __LINE__, __FUNCTION__, \
 #      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #  128 |                  level, \
 #      |                  ~~~~~~~~
 #  129 |                  format, ##__VA_ARGS__); \
 #      |                  ~~~~~~~~~~~~~~~~~~~~~~
sssd-2.4.3/src/responder/pam/pamsrv_cmd.c:1947:53: note: format string is defined here
 # 1947 |     DEBUG(SSSDBG_TRACE_ALL, "PAM initgroups scheme [%s].\n",
 #      |                                                     ^~
```

Reviewed-by: Pavel Březina <pbrezina@redhat.com>
Reviewed-by: Pawel Polawski <ppolawsk@redhat.com>
Reviewed-by: Tomáš Halman <thalman@redhat.com>