BUILD: Fix build without ssh
autoreconf -if
./configure --without-ssh
make check

src/tests/cmocka/test_utils-test_sss_ssh.o: In function `test_textual_public_key':
src/tests/cmocka/test_sss_ssh.c:78: undefined reference to `sss_ssh_format_pubkey'
src/tests/cmocka/test_sss_ssh.c:82: undefined reference to `sss_ssh_format_pubkey'
src/tests/cmocka/test_sss_ssh.c:86: undefined reference to `sss_ssh_format_pubkey'
src/tests/cmocka/test_sss_ssh.c:89: undefined reference to `sss_ssh_format_pubkey'
src/tests/cmocka/test_sss_ssh.c:92: undefined reference to `sss_ssh_format_pubkey'
src/tests/cmocka/test_utils-test_sss_ssh.o:src/tests/cmocka/test_sss_ssh.c:95:
    more undefined references to `sss_ssh_format_pubkey' follow
collect2: error: ld returned 1 exit status

Reviewed-by: Fabiano Fidêncio <fidencio@redhat.com>
(cherry picked from commit d82ffa52dd4c3bb11115b1687edc189284797329)
(cherry picked from commit f46d1474b7b249eda690e78b02adea981fbb058c)