CONFIGURE: Prefer python2
The configure script failed with python3

checking for python... /usr/bin/python
checking for python version... 3.3
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.3/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python3.3/site-packages
checking for headers required to compile python extensions...   File "<string>", line 1
    import sys; print sys.prefix
                        ^
SyntaxError: invalid syntax
  File "<string>", line 1
    import sys; print sys.exec_prefix
                        ^
SyntaxError: invalid syntax
not found
configure: error: Could not find python headers

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
Reviewed-by: Pavel Reichl <preichl@redhat.com>