autofs_test_client and sss_tools: remove store statements from never read variables
New values were stored in two variables that were never read afterwards:
```
Error: CLANG_WARNING:
sssd-2.3.0/src/sss_client/autofs/autofs_test_client.c:59:13: warning:
Although the value stored to 'ret' is used in the enclosing expression,
the value is never actually read from 'ret'
 #    while ((ret = poptGetNextOpt(pc)) > 0)
 #            ^     ~~~~~~~~~~~~~~~~~~
sssd-2.3.0/src/sss_client/autofs/autofs_test_client.c:59:13: note:
Although the value stored to 'ret' is used in the enclosing expression,
the value is never actually read from 'ret'
 #    while ((ret = poptGetNextOpt(pc)) > 0)
 #            ^     ~~~~~~~~~~~~~~~~~~
 #   57|       poptSetOtherOptionHelp(pc, "MAPNAME");
 #   58|
 #   59|->     while ((ret = poptGetNextOpt(pc)) > 0)
 #   60|           ;
 #   61|

Error: CLANG_WARNING:
sssd-2.3.0/src/tools/common/sss_tools.c:73:13: warning: Although the
value stored to 'opt' is used in the enclosing expression, the value is
never actually read from 'opt'
 #    while ((opt = poptGetNextOpt(pc)) != -1) {
 #            ^     ~~~~~~~~~~~~~~~~~~
sssd-2.3.0/src/tools/common/sss_tools.c:73:13: note: Although the value
stored to 'opt' is used in the enclosing expression, the value is never
actually read from 'opt'
 #    while ((opt = poptGetNextOpt(pc)) != -1) {
 #            ^     ~~~~~~~~~~~~~~~~~~
 #   71|
 #   72|       pc = poptGetContext(argv[0], orig_argc, argv, options, 0);
 #   73|->     while ((opt = poptGetNextOpt(pc)) != -1) {
 #   74|           /* do nothing */
 #   75|       }
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>