nss: remove unused label
After 4937f2c6, Sumit noticed the following warning/breakage:

    make[2]: Leaving directory '/home/sbose/sssd/master_build/src/man'
    Making check in .
    make[2]: Entering directory '/home/sbose/sssd/master_build'
      CC       src/responder/nss/nss_protocol_grent.o
    ../src/responder/nss/nss_protocol_grent.c: In function 'nss_protocol_fill_initgr':
    ../src/responder/nss/nss_protocol_grent.c:409:1: error: label 'done' defined but not used [-Werror=unused-label]
     done:
     ^~~~
    cc1: all warnings being treated as errors
    Makefile:17808: recipe for target 'src/responder/nss/nss_protocol_grent.o' failed
    make[2]: *** [src/responder/nss/nss_protocol_grent.o] Error 1
    make[2]: Leaving directory '/home/sbose/sssd/master_build'

Also, while removing the label, by moving the error treatment to the if
block just before the existing one makes the code cleaner.

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>