Tests: don't fail if chattr file doesn't exist
error: DEBUG - chattr: Operation not supported while reading flags on /etc/resolv.conf

Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>