test_ad_common: Include missing header if building with NSS
There was a compile time warning if building with NSS crypto
libraries.

src/tests/cmocka/test_ad_common.c: In function ‘main’:
src/tests/cmocka/test_ad_common.c:873:5: error: implicit declaration of function ‘nspr_nss_cleanu’ [-Werror=implicit-function-declaration]
     nspr_nss_cleanup();
     ^~~~~~~~~~~~~~~~

Reviewed-by: Pavel Reichl <preichl@redhat.com>