TOOLS: Fix warning Wsign-compare
src/tools/tools_util.c: In function ‘parse_groups’:
src/tools/tools_util.c:116:19: error: comparison between
    signed and unsigned integer expressions [-Werror=sign-compare]
     for (i = 0; i < tokens; i++) {
                   ^

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit d3f14ed93ef61268d0a68898ed9c44b4f773081c)