PAM: Fix problem with missing declaration.
The functions strdup and strncmp are used in pam_test_client,
but header file string.h was not included directly in this file.
The header file string.h was indirectly included by the header file
security/pam_client.h.

src/sss_client/pam_test_client.c: In function 'main':
src/sss_client/pam_test_client.c:45:
    error: implicit declaration of function 'strdup'
src/sss_client/pam_test_client.c:45:
    warning: incompatible implicit declaration of built-in function 'strdup'
src/sss_client/pam_test_client.c:49:
    warning: incompatible implicit declaration of built-in function 'strdup'
src/sss_client/pam_test_client.c:52:
    warning: incompatible implicit declaration of built-in function 'strdup'
src/sss_client/pam_test_client.c:64:
    error: implicit declaration of function 'strncmp'
gmake[2]: *** [src/sss_client/pam_test_client.o] Error 1

sh-4.2$ nm --undefined-only ./pam_test_client | grep -E "strdup|strncmp"
                 U __strdup@@GLIBC_2.2.5
                 U strncmp@@GLIBC_2.2.5

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit 654f1abaec4e26453cb88ef02a8a71ba9aea0026)