Allow unknown operation system build
There are various operating systems in the world, and there are even
more if considering the embedded world.

Trying to detect all of them is hardwork and unnecessary.

If the host operating system is uncaught, the configure succeeds with
the following incomplete output:

	./configure
	(...)
	configure: Detected operating system type:
	configure: Build with  config
	---------------------^^

This enables the operating system "unknown" to remove the error raised
and to allow setting a system that is the short list.

It allows the use for options --with-os=unknown or --with-os=arch that
are a often more representative if the operating system is not in the
short list.

It turns:

	./configure --with-os=unknown
	(...)
	configure: error: Illegal value -unknown- for option --with-os

Into:

	./configure --with-os=unknown
	configure: Detected operating system type: unknown
	configure: Build with unknown config

Also, it avoids the assumption the target operating system is the same
as host if cross-compiling, and leads to errors.

For example, the commit e6ae55d5423434d5dc6c236e8647b33610d30e2e passes
the downstream debian option --install-layout=deb to setup.py and raises
an error if targetting a non-debian world (such as openembedded).

Fixes:

	error: option --install-layout not recognized

Signed-off-by: Gaël PORTAY <gael.portay@rtone.fr>