TESTS: Relax the assert in test_idle_timeout
Resolves:
    https://pagure.io/SSSD/sssd/issue/3473

We're being quite strict in test_idle_timeout when checking for the
number of open fds which leads to spurious failures like:
=================================== FAILURES ===================================
______________________________ test_idle_timeout _______________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/ci/label/fedora23/src/tests/intg/test_secrets.py", line 427, in test_idle_timeout
    assert nfds_pre + 1 == nfds_conn
AssertionError: assert (27 + 1) == 27
==================== 1 failed, 221 passed in 473.37 seconds ====================

This is just a check that "a" connection was opened, so we don't have to
check for exact match, but just for larger-or-equal.