PAM: fixes following issue:
```
 Error: RESOURCE_LEAK (CWE-772):
 sssd-2.9.1/src/responder/pam/pamsrv_gssapi.c:750: alloc_arg: ""gss_accept_sec_context"" allocates memory that is stored into ""client_name"".
 sssd-2.9.1/src/responder/pam/pamsrv_gssapi.c:806: leaked_storage: Variable ""client_name"" going out of scope leaks the storage it points to.
 #  804|       gss_release_buffer(&minor, &output);
 #  805|
 #  806|->     return ret;
 #  807|   }
 #  808|
```

Reviewed-by: Justin Stephenson <jstephen@redhat.com>
(cherry picked from commit ad7dc210f79e9b521ff26449d10a0348debff4a8)