ldap: fix unused state
/shared/workspace/sssd/src/providers/ldap/ldap_id.c: In function 'sdap_handle_acct_req_recv':
/shared/workspace/sssd/src/providers/ldap/ldap_id.c:1623:40: error: variable 'state' set but not used [-Werror=unused-but-set-variable=]
1623 | struct sdap_handle_acct_req_state *state;

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>
Reviewed-by: Pavel Březina <pbrezina@redhat.com>
Reviewed-by: Sumit Bose <sbose@redhat.com>