cert: fix assignment discards _const_ qualifier from pointer target type
```
/shared/workspace/sssd/src/util/cert/libcrypto/cert.c:307:17: error: assignment discards _const_ qualifier from pointer target type [-Werror=discarded-qualifiers]
  307 |     rsa_pub_key = EVP_PKEY_get0_RSA(cert_pub_key);
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>
(cherry picked from commit e4d75912a6c243ab8192eca7588df67af2f695a7)