db/sysdb.c: remove unused variable
The variable was set with a value that was never read afterwards:
```
Error: CLANG_WARNING:
sssd-2.3.0/src/db/sysdb.c:2109:9: warning: Value stored to 'ret' is never read
 #        ret = EIO;
 #        ^     ~~~
sssd-2.3.0/src/db/sysdb.c:2109:9: note: Value stored to 'ret' is never read
 #        ret = EIO;
 #        ^     ~~~
 # 2107|           return true;
 # 2108|       } else if (res->count != 1) {
 # 2109|->         ret = EIO;
 # 2110|           goto done;
 # 2111|       }
```

Reviewed-by: Pawel Polawski <ppolawsk@redhat.com>