SSSDConfigTest: Use unique temporary directory
Test SSSDConfigTest is executed twice with make check
if python2 and python3 are available.
Tests are executed in parallel with new automake
and therefore it caused sometimes failures e.g.

ERROR: testModifyExistingConfig (__main__.SSSDConfigTestValid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sssd/src/config/SSSDConfigTest.py", line 215, in testModifyExistingConfig
    mode = os.stat(of)[ST_MODE]
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/testModifyExistingConfig.conf'

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>