TOOLS: Fix warning maybe-uninitialized
src/tools/files.c: In function ‘copy_file_contents’:
src/tools/files.c:413:12: error: ‘ret’ may be used uninitialized in this
     function [-Werror=maybe-uninitialized]
     return ret;
            ^~~

Reviewed-by: Pavel Březina <pbrezina@redhat.com>
(cherry picked from commit c2e3176eaff7c219d63f328570a79f6e5b6f4aec)