p11_child: Fix warning cast discards ‘const’ qualifier from pointer target type
The function process_responder had parameter port defined as const and
it was used in macro BIO_set_conn_port which cast 2nd parameter to
(char*)

  # define BIO_set_conn_port(b,port)     BIO_ctrl(b,BIO_C_SET_CONNECT,1, \
                                                 (char *)(port))

src/p11_child/p11_child_openssl.c: In function ‘process_responder’:
src/p11_child/p11_child_openssl.c:157:9: error: cast discards ‘const’ qualifier from pointer target type [-Werror=cast-qual]
         BIO_set_conn_port(cbio, port);
         ^~~~~~~~~~~~~~~~~

Merges: https://pagure.io/SSSD/sssd/pull-request/3880

Reviewed-by: Sumit Bose <sbose@redhat.com>