SPEC: Move polkit rules into sssd-polkit-rules subpackage
We recently added /usr/share/polkit-1/rules.d to the spec file
to fix issues with unowned directories. However there is conflict
with polkit package. The owner is not root.

Running transaction test
Error: Transaction check error:
  file /usr/share/polkit-1/rules.d from install of sssd-common-1.13.90-0.20160125.1503.git1b8858b.master.f
+c23.x86_64 conflicts with file from package polkit-0.113-4.fc23.x86_64

Reviewed-by: Lukáš Slebodník <lslebodn@redhat.com>