pam-srv-tests: Fix warning unused-function
If pam-srv-tests is not build with NSS support then
certificate related test are not executed and therefore
there is unused setup function pam_test_setup_no_verification.

src/tests/cmocka/test_pam_srv.c:323:12: error:
    'pam_test_setup_no_verification' defined but not used
    [-Werror=unused-function]
 static int pam_test_setup_no_verification(void **state)
            ^

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>