monitor: fix unused variable warning
```
src/monitor/monitor.c: In function ‘get_monitor_config’:
src/monitor/monitor.c:898:9: error: unused variable ‘timeout_seconds’ [-Werror=unused-variable]
  898 |     int timeout_seconds;
```

Introduced in c4c0fd690d82f9a8a714784ad4e036a39e1017fc.

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>