Secrets: Fix format string
body->length has type size_t and not long unsigned.
size_t does not have the same size on 64 bit and 32 bit platform

src/responder/secrets/providers.c: In function 'sec_http_reply_with_body':
src/responder/secrets/providers.c:204:25: error: format '%lu' expects argument
  of type 'long unsigned int', but argument 6 has type
  'size_t {aka unsigned int}' [-Werror=format=]
                         "HTTP/1.1 %d %s\r\n"
                         "Content-Type: %s\r\n"
                         "Content-Length: %lu\r\n"
                         ^
Reviewed-by: Sumit Bose <sbose@redhat.com>