MONITOR: Fix warning may be used uninitialized
This warning is caused be change 579e5d4b7a3ca161ea7518b2996905fa22c15995
"MONITOR: Allow confdb to be accessed by nonroot user"

src/monitor/monitor.c: In function ‘main’:
src/monitor/monitor.c:2953:24: error: ‘monitor’ may be used uninitialized
                               in this function [-Werror=maybe-uninitialized]
     monitor->is_daemon = !opt_interactive;
                        ^
cc1: all warnings being treated as errors

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
Reviewed-by: Lukáš Slebodník <lslebodn@redhat.com>