SPEC: Fix detecting of minor release
INFO: Installed packages:
Start: build phase for sssd-1.15.4-0.el7.src.rpm
Start: build setup for sssd-1.15.4-0.el7.src.rpm
error: unmatched (
error: unmatched (
error: /builddir/build/SPECS/sssd.spec:56: bad %if condition

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit c20a9efbf5da0587fbb6a855a2d366ce19f1abe1)
(cherry picked from commit b788aaa4341bcd0c1f0fc3081c540af958de8d45)