BUILD: Add missing header file to tarball
make distcheck failed due to missing header file.

  ../src/tests/cmocka/test_ldap_auth.c:33:45:
     fatal error: tests/cmocka/test_expire_common.h: No such file or directory
  #include "tests/cmocka/test_expire_common.h"
                                            ^
  compilation terminated.

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>