fix warnings around sss_getenv()
Introduced in
- 44525a9995c775ac284a6203d0e505dc4bf0d459
- c1dd121142fb22648793a38e45257b348d658460

```
/home/pbrezina/workspace/sssd/src/db/sysdb_init.c: In function ‘sysdb_ldb_connect’:
/home/pbrezina/workspace/sssd/src/db/sysdb_init.c:82:49: error: passing argument 3 of ‘sss_getenv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   82 |     ret = sss_getenv(tmp_ctx, LDB_MODULES_PATH, &mod_path);
      |                                                 ^~~~~~~~~
      |                                                 |
      |                                                 const char **
In file included from /home/pbrezina/workspace/sssd/src/db/sysdb_init.c:23:
/home/pbrezina/workspace/sssd/src/util/util.h:806:75: note: expected ‘char **’ but argument is of type ‘const char **’
  806 | errno_t sss_getenv(TALLOC_CTX *mem_ctx, const char *variable_name, char **_value);

/home/pbrezina/workspace/sssd/src/providers/files/files_init.c: In function ‘files_init_file_sources’:
/home/pbrezina/workspace/sssd/src/providers/files/files_init.c:61:26: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   61 |         dfl_passwd_files = DEFAULT_PASSWD_FILE;
      |                          ^
/home/pbrezina/workspace/sssd/src/providers/files/files_init.c:77:25: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   77 |         env_group_files = DEFAULT_GROUP_FILE;
      |                         ^
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>