BUILD: fixes gpo_child linking issue
/usr/bin/ld: src/util/gpo_child-signal.o (symbol from plugin): undefined reference to symbol 'BlockSignals@@SAMBA_UTIL_0.0.1'

Resolves: https://github.com/SSSD/sssd/issues/5385

Reviewed-by: Pavel Březina <pbrezina@redhat.com>
(cherry picked from commit d547a2dc1803ec10cbeda2b27b92ecc97adfd24b)

Reviewed-by: Pavel Březina <pbrezina@redhat.com>