pysss: use METH_VARARGS | METH_KEYWORDS instead of just METH_KEYWORDS
To fix this error that happened during mockbuild on rawhide.

FAIL: src/tests/pysss-test.py3
==============================
ERROR: test_import (__main__.PysssImport)
Import the module and assert it comes from tree
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/builddir/build/BUILD/sssd-1.16.5/src/tests/pysss-test.py", line 56, in test_import
   import pysss
 SystemError: bad call flags

In Python 3.7, import didn't check descriptor flags (METH_KEYWORDS):
these flags were only checked when the methods were called.

In Python 3.8, the flags are checked as soon as the module is imported,
which prevents the module to be imported.

Inspired by:
https://github.com/rpm-software-management/libcomps/pull/50

Python doc:
https://docs.python.org/3/c-api/structures.html#METH_VARARGS

Reviewed-by: Tomáš Halman <thalman@redhat.com>