test_resolv_fake: Fix alignment warning
src/tests/cmocka/test_resolv_fake.c:60:9:
    error: cast from 'uint8_t *' (aka 'unsigned char *') to 'HEADER *'
    increases required alignment from 1 to 4 [-Werror,-Wcast-align]

    h = (HEADER *) hb;
        ^~~~~~~~~~~~~
1 error generated.

Reviewed-by: Michal Židek <mzidek@redhat.com>