responder/common/responder_packet: get packet length only once
Packet length variable was read and then read again without using the
previously read value. So, I have refactored the code a little bit to
read the value once and use it everywhere else. Moreover, I have
implemented some improvements in sss_packet_recv() function pointed by
Alexey.

Coverity errors:
```
Error: CLANG_WARNING:
sssd-2.3.0/src/responder/common/responder_packet.c:217:21: warning:
Although the value stored to 'new_len' is used in the enclosing
expression, the value is never actually read from 'new_len'
 #                && (new_len = sss_packet_get_len(packet))
 #                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~
sssd-2.3.0/src/responder/common/responder_packet.c:217:21: note:
Although the value stored to 'new_len' is used in the enclosing
expression, the value is never actually read from 'new_len'
 #                && (new_len = sss_packet_get_len(packet))
 #                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~
 #  215|                       || sss_packet_get_cmd(packet) == SSS_NSS_GETLISTBYCERT)
 #  216|                   && packet->memsize < SSS_CERT_PACKET_MAX_RECV_SIZE
 #  217|->                 && (new_len = sss_packet_get_len(packet))
 #  218|                                      < SSS_CERT_PACKET_MAX_RECV_SIZE) {
 #  219|               new_len = sss_packet_get_len(packet);
```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>
Reviewed-by: Pavel Březina <pbrezina@redhat.com>
(cherry picked from commit 5d9e2328ce1706acf87e09b588e134e0f2b761c8)

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>