intg: Increase startup timeouts for secrets
In cwrap environment, we start sssd_secrets ourself
and not by systemd socket activation. Our approach is to wait a second in
a loop till socket is available. However sometimes 1 second is not enough.
Patch increases wait timeout from 1 second to 10 and it seems to be enough even
when processes were executed with valgrind.

Traceback (most recent call last):
  File "src/tests/intg/test_secrets.py", line 419, in setup_for_cli_timeout_test
    return create_sssd_secrets_fixture(request)
  File "src/tests/intg/test_secrets.py", line 82, in create_sssd_secrets_fixture
    assert os.path.exists(sock_path)
AssertionError: assert False
 +  where False = <function exists at 0x7f6c1cf520c8>('/tmp/sssd-intg.cdv0namx/var/run/secrets.socket')
 +    where <function exists at 0x7f6c1cf520c8> = <module 'posixpath' from '/usr/lib64/python2.7/posixpath.pyc'>.exists
 +      where <module 'posixpath' from '/usr/lib64/python2.7/posixpath.pyc'> = os.path

Resolves:
https://pagure.io/SSSD/sssd/issue/3481

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit dc5da74112bde32b0bd33d9304f7e94eb8ed2885)