intg: Fix creating of slapd configuration
The python module subprocess expect bytes as an input.

Traceback (most recent call last):
  File "src/tests/intg/test_ldap.py", line 51, in ds_inst
    ds_inst.setup()
  File "src/tests/intg/ds_openldap.py", line 201, in setup
    self._setup_config()
  File "src/tests/intg/ds_openldap.py", line 169, in _setup_config
    slapadd.communicate(config)
  File "/usr/lib64/python3.6/subprocess.py", line 821, in communicate
    self._stdin_write(input)
  File "/usr/lib64/python3.6/subprocess.py", line 776, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'