SSSDConfig: Handle integer parsing more leniently
debug_level is usually defined as decimal value <= 10
or as a hexadecimal value which is used as a bitmask

Parsing of hexadecimal value was partially fixed by commit
7fac271ccebb84743c39f553eb5ec013cf1d10aa but only for
sssd domains. It was not fixed for sssd services.

  File "/usr/share/authconfig/authinfo.py", line 3142, in writeSSSDPAM
    pam = self.sssdConfig.get_service('pam')
  File "/usr/lib/python3.6/site-packages/SSSDConfig/__init__.py", line 1620, in get_service
    service.set_option(opt['name'], opt['value'])
  File "/usr/lib/python3.6/site-packages/SSSDConfig/__init__.py", line 932, in set_option
    (option_schema[0], optionname, type(value)))
TypeError: Expected <class 'int'> for debug_level, received <class 'str'>

Resolves:
https://pagure.io/SSSD/sssd/issue/3410