sss_sockets: pass pointer instead of integer
```
/home/pbrezina/workspace/sssd/src/util/sss_sockets.c: In function ‘set_fd_common_opts’:
/home/pbrezina/workspace/sssd/src/util/sss_sockets.c:123:61: error: passing argument 4 of ‘setsockopt’ makes pointer from integer without a cast [-Werror=int-conversion]
  123 |         ret = setsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT, milli,
      |                                                             ^~~~~
      |                                                             |
      |                                                             unsigned int
In file included from /home/pbrezina/workspace/sssd/src/util/sss_sockets.c:28:
/usr/include/sys/socket.h:216:22: note: expected ‘const void *’ but argument is of type ‘unsigned int’
  216 |          const void *__optval, socklen_t __optlen) __THROW;
      |          ~~~~~~~~~~~~^~~~~~~~
  CC       src/util/sssd_kcm-sss_iobuf.o
cc1: all warnings being treated as errors
```

Introduced by 7aa96458f3bec4ef6ff7385107458e6b2b0b06ac

Reviewed-by: Sumit Bose <sbose@redhat.com>
(cherry picked from commit 5b87af6f5b50c464ee7ea4558f73431e398e1423)